architect:
  - andreychh
assets:
  docker_password: andreychh/secrets#assets/docker-hub-password
merge:
  script: |
    echo "Merging branch..."
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
    repo="andreychh/coopera"
    commit=$(git rev-parse --short HEAD)
    cat ../docker_password | sudo docker login --username andreychh --password-stdin
    DOCKER_BUILDKIT=1 sudo docker build --build-arg "VERSION=${tag}" --build-arg "COMMIT=${commit}" --tag "${repo}:${tag}" "$(pwd)"
    sudo docker push "${repo}:${tag}"
