name: markdownlint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdownlint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v20.0.0
        with:
          globs: '**/*.{md,markdown}'
